[book]
title = "HXLX"
language = "en"
src = "src"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
# copy-fonts = true
# copy-custom-fonts = true

additional-js = []
additional-css = []

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = true          # displays a run button for rust code



[preprocessor.mermaid-panzoom]
command = "mdbook-mermaid-panzoom"

# [preprocessor.mermaid]
# command = "mdbook-mermaid"
