# /HXLX/book.toml
[book]
title = "HXLX"
language = "en"
src = "src"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"

additional-js = [
  "src/assets/mermaid.min.js",
  "src/assets/panzoom-bundle.js"
]
additional-css = [
 "src/assets/panzoom.css",
]

[preprocessor.mermaid-panzoom]
command = "mdbook-mermaid-panzoom"

[preprocessor.components]
command = "mdbook-components"
namespace = "mybook"
strict = false
debug = true

[preprocessor.components.components.admonition]
template = "./components/admonition/model.html"
css = "./components/admonition/view.css"
js = "./components/admonition/control.js"

[preprocessor.components.components.admonition.schema]
required = ["type", "title"]
optional = ["icon", "collapsible"]
